version: '3.4'

services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    ports:
      - 3001:3000
    volumes:
      - './frontend:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ./backend/APIGateway/Dockerfile

  servicepost:
    image: ${DOCKER_REGISTRY-}servicepost
    build:
      context: .
      dockerfile: ./backend/ServicePost/Dockerfile
    depends_on:
      - socialform_web_app

  imageapi:
    image: ${DOCKER_REGISTRY-}imageapi
    build:
      context: .
      dockerfile: ./backend/ImageApi/Dockerfile
    volumes:
      - ./ImageApi/UploadImages:/app/UploadImages
