---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: 434565/apigateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: apigateway
  ports:
    - name: apigateway-port
      protocol: TCP
      port: 8080
      targetPort: 80
