apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-servicepost
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicepost-depl
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
