apiVersion: v1
kind: Service
metadata:
  name: frontend-srv
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: frontendport
      protocol: TCP
      port: 80
      targetPort: 80
