---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: imageapi
    spec:
      containers:
        - name: imageapi
          image: 434565/imageapi:latest
  selector:
    matchLabels:
      app: imageapi
---
apiVersion: v1
kind: Service
metadata:
  name: imageapi-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: imageapi
  ports:
    - name: imageapi
      protocol: TCP
      port: 80
      targetPort: 80
