---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicepost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicepost
    spec:
      containers:
        - name: servicepost
          image: 434565/servicepost:latest
  selector:
    matchLabels:
      app: servicepost
---
apiVersion: v1
kind: Service
metadata:
  name: servicepost-clusterip-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: servicepost
