---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicepost-depl
spec:
  selector:
    matchLabels:
      app: servicepost
  template:
    metadata:
      labels:
        app: servicepost
    spec:
      containers:
        - name: servicepost
          image: 434565/servicepost:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: servicepost-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: servicepost
  ports:
    - name: servicepost
      protocol: TCP
      port: 80
      targetPort: 80
