---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicecomment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicecomment
    spec:
      containers:
        - name: servicecomment
          image: 434565/servicecomment:latest
  selector:
    matchLabels:
      app: servicecomment
---
apiVersion: v1
kind: Service
metadata:
  name: servicecomment-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: servicecomment
  ports:
    - name: servicecomment
      protocol: TCP
      port: 80
      targetPort: 80
