version: '3.4'

services:
  rabbit:
    image: rabbitmq:3.7.2-management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  imageapi:
    image: ${DOCKER_REGISTRY-}imageapi
    build:
      context: .
      dockerfile: ImageApi/Dockerfile

  servicepost:
    image: ${DOCKER_REGISTRY-}servicepost
    build:
      context: .
      dockerfile: ServicePost/Dockerfile

  servicecomment:
    image: ${DOCKER_REGISTRY-}servicecomment
    build:
      context: .
      dockerfile: ServiceComments/Dockerfile

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    ports:
      - 3001:3000
    volumes:
      - './frontend:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
