name: Back-end CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd PolarGram
        dotnet restore APIGateway
        dotnet restore ImageApi
        dotnet restore ServicePost
        
    - name: Build
      run: |
        cd PolarGram
        dotnet build --configuration Release --no-restore APIGateway
        dotnet build --configuration Release --no-restore ImageApi
        dotnet build --configuration Release --no-restore ServicePost
    
    - name: Build and Push Docker Image
      run: |
        cd PolarGram/APIGateway
        uses: mr-smithers-excellent/docker-build-push@v4
        with: 
          image: 434565/apigateway
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      
    #- name: Test
    #  run: |
    #    cd PolarGram
    #    dotnet test TestServicePost
