name: Back-end CI

on:
  push:
    branches: 
      - master
    paths:
      - SocialformAPI/**
  pull_request:
    branches: 
      - master
    paths:
      - SocialformAPI/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd SocialformAPI
        dotnet restore APIGateway
        dotnet restore CommentService
        dotnet restore ImageApi
        dotnet restore LikeService
        dotnet restore PostService
        
    - name: Build
      run: |
        cd SocialformAPI
        dotnet build --configuration Release --no-restore APIGateway
        dotnet build --configuration Release --no-restore CommentService
        dotnet build --configuration Release --no-restore ImageApi
        dotnet build --configuration Release --no-restore LikeService
        dotnet build --configuration Release --no-restore PostService
      
    - name: Test
      run: |
        cd SocialformAPI
        dotnet test PostServiceTests
