name: Back-end CI

on:
  push:
    branches: 
      - master
    paths:
      - PolarGram/**
  pull_request:
    branches: 
      - master
    paths:
      - PolarGram/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd backend
        dotnet restore APIGateway
        dotnet restore ImageApi
        dotnet restore ServicePost
        
    - name: Build
      run: |
        cd backend
        dotnet build --configuration Release --no-restore APIGateway
        dotnet build --configuration Release --no-restore ImageApi
        dotnet build --configuration Release --no-restore ServicePost
      
    - name: Test
      run: |
        cd backend
        dotnet test TestServicePost
